#pragma once
#include <dinput.h>

enum class KeyCode : unsigned int
{
	ESCAPE = DIK_ESCAPE,
	Zero = DIK_0,
	One = DIK_1,
	Two = DIK_2,
	Three = DIK_3,
	Four = DIK_4,
	Five = DIK_5,
	Six = DIK_6,
	Seven = DIK_7,
	Eight = DIK_8,
	Nine = DIK_9,
	Minus = DIK_MINUS,
	Equals = DIK_EQUALS,
	Back = DIK_BACK,
	Tab = DIK_TAB,
	Q = DIK_Q,
	W = DIK_W,
	E = DIK_E,
	R = DIK_R,
	T = DIK_T,
	Y = DIK_Y,
	U = DIK_U,
	I = DIK_I,
	O = DIK_O,
	P = DIK_P,
	A = DIK_A,
	S = DIK_S,
	D = DIK_D,
	F = DIK_F,
	G = DIK_G,
	H = DIK_H,
	J = DIK_J,
	K = DIK_K,
	L = DIK_L,
	Z = DIK_Z,
	X = DIK_X,
	C = DIK_C,
	V = DIK_V,
	B = DIK_B,
	N = DIK_N,
	M = DIK_M,
	LBrancket = DIK_LBRACKET,
	RBrancket = DIK_RBRACKET,
	Return = DIK_RETURN,
	Space = DIK_SPACE,
	LControll = DIK_LCONTROL,
	RControll = DIK_RCONTROL,
	Semicolon = DIK_SEMICOLON,
	Apostrophe = DIK_APOSTROPHE,
	Grave = DIK_GRAVE,
	LShift = DIK_LSHIFT,
	Rshift = DIK_RSHIFT,
	Comma = DIK_COMMA,
	Period = DIK_PERIOD,
	Slash = DIK_SLASH,
	BackSlash = DIK_BACKSLASH,
	BackSpace = DIK_BACKSPACE,
	Multiply = DIK_MULTIPLY,
	LMenu = DIK_LMENU,
	RMenu = DIK_RMENU,
	Capital = DIK_CAPITAL,
	F1 = DIK_F1,
	F2 = DIK_F2,
	F3 = DIK_F3,
	F4 = DIK_F4,
	F5 = DIK_F5,
	F6 = DIK_F6,
	F7 = DIK_F7,
	F8 = DIK_F8,
	F9 = DIK_F9,
	F10 = DIK_F10,
	F11 = DIK_F11,
	F12 = DIK_F12,
	F13 = DIK_F13,
	F14 = DIK_F14,
	F15 = DIK_F15,
	NumLock = DIK_NUMLOCK,
	Scroll = DIK_SCROLL,
	Numpad0 = DIK_NUMPAD0,
	Numpad1 = DIK_NUMPAD1,
	Numpad2 = DIK_NUMPAD2,
	Numpad3 = DIK_NUMPAD3,
	Numpad4 = DIK_NUMPAD4,
	Numpad5 = DIK_NUMPAD5,
	Numpad6 = DIK_NUMPAD6,
	Numpad7 = DIK_NUMPAD7,
	Numpad8 = DIK_NUMPAD8,
	Numpad9 = DIK_NUMPAD9,
	Subtract = DIK_SUBTRACT,
	Add = DIK_ADD,
	Decimal = DIK_DECIMAL,
	Oem102 = DIK_OEM_102,
	AbntC1 = DIK_ABNT_C1,
	AbntC2 = DIK_ABNT_C2,
	Convert = DIK_CONVERT,
	Noconvert = DIK_NOCONVERT,
	Yen = DIK_YEN,
	Kana = DIK_KANA,
	Kanji = DIK_KANJI,
	NumpadEquals = DIK_NUMPADEQUALS,
	NumpadEnter = DIK_NUMPADENTER,
	PrevTrack = DIK_PREVTRACK,
	At = DIK_AT,
	Colon = DIK_COLON,
	Underscore = DIK_UNDERLINE,
	Stop = DIK_STOP,
	Ax = DIK_AX,
	Unlabeled = DIK_UNLABELED,
	NextTrack = DIK_NEXTTRACK,
	Mute = DIK_MUTE,
	Calculator = DIK_CALCULATOR,
	MediaStop = DIK_MEDIASTOP,
	MediaSelect = DIK_MEDIASELECT,
	PlayPause = DIK_PLAYPAUSE,
	VolUp = DIK_VOLUMEUP,
	VolDown = DIK_VOLUMEDOWN,
	WebHome = DIK_WEBHOME,
	NumpadComma = DIK_NUMPADCOMMA,
	Divide = DIK_DIVIDE,
	Sysrq = DIK_SYSRQ,
	Pause = DIK_PAUSE,
	Home = DIK_HOME,
	Up = DIK_UP,
	Down = DIK_DOWN,
	Left = DIK_LEFT,
	Right = DIK_RIGHT,
	UpArrow = DIK_UPARROW,
	DownArrow = DIK_DOWNARROW,
	LeftArrow = DIK_LEFTARROW,
	RightArrow = DIK_RIGHTARROW,
	PgUp = DIK_PRIOR,
	PgDn = DIK_NEXT,
	End = DIK_END,
	Insert = DIK_INSERT,
	Delete = DIK_DELETE,
	LWin = DIK_LWIN,
	RWin = DIK_RWIN,
	Apps = DIK_APPS,
	Sleep = DIK_SLEEP,
	Wake = DIK_WAKE,
	WebSearch = DIK_WEBSEARCH,
	WebFavorites = DIK_WEBFAVORITES,
	WebStop = DIK_WEBSTOP,
	WebForward = DIK_WEBFORWARD,
	WebBack = DIK_WEBBACK,
	MyComputer = DIK_MYCOMPUTER,
	Mail = DIK_MAIL,
};

inline unsigned int operator|(KeyCode &a, KeyCode &b)
{
	return static_cast<unsigned int>(a) | static_cast<unsigned int>(b);
}

inline unsigned int operator&(KeyCode &a, KeyCode &b)
{
	return static_cast<unsigned int>(a) & static_cast<unsigned int>(b);
}